In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('TTO_dataset_410.csv')
df

,row_idx,YEAR,DATE,GAME_ID,INNING,PIT_ID,BAT_ID,WOBA_APP,EVENT_WOBA_19,HAND_MATCH,BAT_HOME_IND,PITCH_COUNT_CUMU,PIT_IS_BAT,BATTER_SEQ_NUM,ORDER_CT,BATTER_IDX
0,58505,2006,2006-04-07,ANA200604070,1,escok001,damoj001,True,0.000,0.0,0,9,False,1,1,1
1,58506,2006,2006-04-07,ANA200604070,1,escok001,jeted001,True,0.870,1.0,0,11,False,2,1,2
2,58507,2006,2006-04-07,ANA200604070,1,escok001,shefg001,True,0.000,1.0,0,14,False,3,1,3
3,58508,2006,2006-04-07,ANA200604070,1,escok001,rodra001,True,0.000,1.0,0,19,False,4,1,4
4,58509,2006,2006-04-07,ANA200604070,1,chacs001,figgc001,True,1.217,1.0,1,4,False,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1653462,5648038,2019,2019-09-29,WAS201909290,6,clevm001,readr002,True,0.000,1.0,1,83,False,21,3,11
1653463,5648039,2019,2019-09-29,WAS201909290,6,clevm001,taylm002,True,0.870,1.0,1,85,False,22,3,12
1653464,5648041,2019,2019-09-29,WAS201909290,6,clevm001,adamm002,True,0.000,0.0,1,90,False,23,3,5
1653465,5648042,2019,2019-09-29,WAS201909290,6,clevm001,roblv001,True,0.690,1.0,1,96,False,24,3,6
1653466,5648044,2019,2019-09-29,WAS201909290,6,clevm001,dozib001,True,0.870,1.0,1,103,False,25,3,7

In [3]:
# df.columns
df.BATTER_IDX.value_counts()

BATTER_IDX
1     211894
2     204655
3     197810
4     191688
5     185712
6     178591
7     170296
8     159371
9     133590
10     16047
11      3154
12       477
13       120
14        44
15        12
16         5
17         1
Name: count, dtype: int64

In [4]:
# df.PIT_ID.nunique()
# for col in df.select_dtypes('object').columns:
#     print(col, df[col].unique())

# print(df.YEAR, df.YEAR.unique())
# print(df.All_Tags.unique())
# print(df.Release_Date.unique())
# print(df.Steam_Deck_Status.unique())
# print(df.Release_Date)
print(df.YEAR.unique())

[2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019]

In [5]:
df_1 = pd.read_csv('TTO_dataset_510.csv')
df_1.head(10)

,YEAR,DATE,GAME_ID,INNING,PIT_ID,BAT_ID,WOBA_APP,EVENT_WOBA_19,HAND_MATCH,BAT_HOME_IND,...,BQ2,std_EVENT_WOBA_19,std_WOBA_FINAL_BAT_19,std_WOBA_FINAL_PIT_19,std_WOBA_CURR_BAT_19,std_WOBA_CURR_PIT_19,std_BQ,std_PQ,std_BQ2,std_PQ2
0,2010,2010-04-04,BOS201004040,1,beckj002,jeted001,True,0.00,1.0,0,...,0.382427,-0.316793,0.019083,0.660909,-1.670337,-2.581598,0.551778,-0.330316,0.545120,-0.250639
1,2010,2010-04-04,BOS201004040,1,beckj002,johnn001,True,0.00,0.0,0,...,0.342030,-0.316793,0.055713,0.660909,-1.670337,-2.581598,0.211474,-0.375530,0.208309,-0.402988
2,2010,2010-04-04,BOS201004040,1,beckj002,teixm001,True,0.00,1.0,0,...,0.405075,-0.316793,0.455796,0.660909,-1.670337,-2.581598,0.742564,-0.419858,0.733947,-0.544052
3,2010,2010-04-04,BOS201004040,1,sabac001,ellsj001,True,0.00,1.0,1,...,0.321310,-0.316793,-0.254727,-0.477714,-1.670337,-2.581598,0.036922,-0.578489,0.035549,-0.465905
4,2010,2010-04-04,BOS201004040,1,sabac001,pedrd001,True,0.00,0.0,1,...,0.365512,-0.316793,0.342260,-0.477714,-1.670337,-2.581598,0.409284,-0.621246,0.404088,-0.609974
5,2010,2010-04-04,BOS201004040,1,sabac001,martv001,True,0.00,1.0,1,...,0.346011,-0.316793,0.345593,-0.477714,-1.670337,-2.581598,0.245011,-0.663165,0.241501,-0.743372
6,2010,2010-04-04,BOS201004040,2,beckj002,rodra001,True,0.00,1.0,0,...,0.383873,-0.316793,0.093429,0.660909,-1.670337,-2.581598,0.563960,-0.463324,0.557177,-0.675040
7,2010,2010-04-04,BOS201004040,2,beckj002,canor001,True,0.00,0.0,0,...,0.351210,-0.316793,0.677594,0.660909,-1.670337,-2.581598,0.288806,-0.505955,0.284848,-0.796994
8,2010,2010-04-04,BOS201004040,2,beckj002,posaj001,True,1.94,1.0,0,...,0.359755,1.650618,0.287018,0.660909,8.548419,0.109800,0.360791,-0.308313,0.356094,-0.183838
9,2010,2010-04-04,BOS201004040,2,beckj002,granc001,True,1.94,0.0,0,...,0.323018,1.650618,0.031632,0.660909,8.548419,2.032227,0.051316,-0.100845,0.049795,0.429962

In [8]:
df_1.columns
# df_1.BQ.value_counts()
df_1.BQ2.value_counts()

BQ2
0.000000    2506
0.293490     196
0.291059     185
0.283863     185
0.286429     180
            ...
0.306591       1
0.315981       1
0.362802       1
0.360004       1
0.313925       1
Name: count, Length: 1148812, dtype: int64

In [6]:
# df_1[df_1['GAME_ID']] == 'BOS201004040'
# 'BOS201004040' in df_1['GAME_ID'].values
# df_1.GAME_ID == 'BOS201004040'
# df_1.GAME_ID.value_counts().get('BOS201004040', 0)
df_1.YEAR.min()

2010

In [7]:
df_2 = pd.read_csv('retro_final_PA_1990-2020d.csv')
df_2

C:\Users\csnak\AppData\Local\Temp\ipykernel_17724\607304963.py:1: DtypeWarning: Columns (16,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2 = pd.read_csv('retro_final_PA_1990-2020d.csv')

,row_idx,GAME_ID,PARK,DATE,YEAR,HOME_TEAM_ID,AWAY_TEAM_ID,INNING,BAT_HOME_IND,BAT_ID,...,WOBA_APP,EVENT_RUNS,EVENT_PITCH_COUNT,PITCH_COUNT_CUMU,PITCH_COUNT_FINAL,DAYS_SINCE_SZN_START,PIT_REST,EVENT_WOBA,EVENT_WOBA_19,BASE_STATE
0,1,ANA199704020,ANA01,1997-04-02,1997,ANA,BOS,1,0,garcn001,...,True,0,3.0,3,93,1.0,6.0,0.000,0.000,0
1,2,ANA199704020,ANA01,1997-04-02,1997,ANA,BOS,1,0,valej002,...,True,0,1.0,4,93,1.0,6.0,1.260,1.217,0
2,3,ANA199704020,ANA01,1997-04-02,1997,ANA,BOS,1,0,vaugm001,...,True,0,5.0,9,93,1.0,6.0,0.714,0.690,10
3,4,ANA199704020,ANA01,1997-04-02,1997,ANA,BOS,1,0,stanm002,...,True,0,3.0,12,93,1.0,6.0,0.000,0.000,110
4,5,ANA199704020,ANA01,1997-04-02,1997,ANA,BOS,1,0,naeht001,...,True,0,2.0,14,93,1.0,6.0,0.000,0.000,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5650376,5650377,WAS202009270,WAS11,2020-09-27,2020,WAS,NYN,8,1,turnt001,...,True,0,8.0,27,27,66.0,4.0,0.000,0.000,10
5650377,5650378,WAS202009270,WAS11,2020-09-27,2020,WAS,NYN,9,0,nimmb001,...,True,0,5.0,25,44,66.0,5.0,0.000,0.000,0
5650378,5650379,WAS202009270,WAS11,2020-09-27,2020,WAS,NYN,9,0,davij006,...,True,0,7.0,32,44,66.0,5.0,0.699,0.690,0
5650379,5650380,WAS202009270,WAS11,2020-09-27,2020,WAS,NYN,9,0,alonp001,...,True,0,7.0,39,44,66.0,5.0,0.000,0.000,100
5650380,5650381,WAS202009270,WAS11,2020-09-27,2020,WAS,NYN,9,0,frazt001,...,True,0,5.0,44,44,66.0,5.0,0.000,0.000,100

In [8]:
df_2.columns

Index(['row_idx', 'GAME_ID', 'PARK', 'DATE', 'YEAR', 'HOME_TEAM_ID',
       'AWAY_TEAM_ID', 'INNING', 'BAT_HOME_IND', 'BAT_ID', 'BAT_NAME',
       'BAT_HAND', 'FIELD_POS', 'PIT_ID', 'PIT_NAME', 'PIT_HAND', 'COUNT',
       'PITCH_SEQ_TX', 'EVENT_TX', 'HIT_VAL', 'HIT_BINARY',
       'consecutive.bat.row', 'BATTER_SEQ_NUM', 'ORDER_CT', 'HAND_MATCH',
       'SP_IND', 'HOME_DIV', 'AWAY_DIV', 'HOME_LEAGUE', 'AWAY_LEAGUE',
       'IN_DIV', 'IN_LEAGUE', 'EVENT_OUTS_CT', 'OUTS_CT', 'EVENT_CODE',
       'PA_IND', 'AB_IND', 'WOBA_APP', 'EVENT_RUNS', 'EVENT_PITCH_COUNT',
       'PITCH_COUNT_CUMU', 'PITCH_COUNT_FINAL', 'DAYS_SINCE_SZN_START',
       'PIT_REST', 'EVENT_WOBA', 'EVENT_WOBA_19', 'BASE_STATE'],
      dtype='object')

In [9]:
# df_2.EVENT_TX.value_counts()
# print(df_2['EVENT_TX'], df_2['EVENT_TX'].unique())
df_2.BAT_HAND.value_counts()

BAT_HAND
R    3030185
L    1752598
B     867598
Name: count, dtype: int64

In [10]:
'BOS201004040' in df_2['GAME_ID'].values
# df_2.GAME_ID.value_counts().get('BOS201004040', 0)

True

In [11]:
df_2.YEAR.max()

2020